Make for authenticated websocket
westwinglabs/coinbase-kotlin pull request #26
Opened 2021-06-26 19:14 UTC by Luckvery

Just adding an entry for running the authenticated websocket code in the demo project.

2021-07-10 14:35 UTC, zugaldia requested changes
Good example @Luckvery! There's a small typo, once it gets fixed (let me know if you want me to do it) I can get this merged. Being an example it won't necessarily need a new release.

2021-07-10 14:35 UTC, zugaldia commented on cli/src/main/kotlin/com/westwinglabs/coinbase/cli/Launcher.kt
> +const val OPTION_WEBSOCKRT_CHANNELS = "channels"
Typo on "websocket."

2021-07-17 15:45 UTC, Luckvery commented on cli/src/main/kotlin/com/westwinglabs/coinbase/cli/Launcher.kt
> +const val OPTION_WEBSOCKRT_CHANNELS = "channels"
Whoops!! 🤦

2021-07-17 15:49 UTC, Luckvery commented on cli/src/main/kotlin/com/westwinglabs/coinbase/cli/Launcher.kt
> +const val OPTION_WEBSOCKRT_CHANNELS = "channels"
Fixed!!

2021-07-18 23:03 UTC, zugaldia approved these changes

2021-07-18 23:03 UTC, merged

2021-07-18 23:03 UTC, zugaldia commented
:rocket: merged @Luckvery !